### ISSUE TITLE
module does not work when only onestepcheckout/iosc is installed

### ISSUE THREAD

**Issue by wdttilburg** [tig-nl/postcode-additional-support-checkouts-magento2#1] opened 2019-10-28 15:32 UTC
**To Reproduce**
1. install only onestepcheckout from iosc, and not Mageplaza onestepcheckout.
2. install module as noted in readme
3. run bin/magento s:d:c

**Expected result**
Generated code and dependency injection configuration successfully.

**Actual result**
[ReflectionException]
Class Mageplaza\Osc\Helper\Data does not exist 

**Workaround**
remove or change all files with mageplaza.

** Please complete the following information**
- Magento version: 2.2.10
- PHP version: 7.1.32

**Comment by tig-dennisvanderhammen** [comment] 2019-10-29 14:39
Hi @wdttilburg,

Thank you for pointing this out!

I'll have to look into this, because I'm not getting this error on my local Magento 2.3.3 environment.

Once I find out more I'll let you know!

**Comment by tig-dennisvanderhammen** [comment] 2019-10-31 12:00
Hi @wdttilburg,

I've managed to reproduce your issue on the Magento version that you mentioned in your issue. I'll give you an update when we have a working fix for this issue!

**Closed as completed** 2020-07-13 09:19 UTC
Labels: bug
